services:
  app_proxy:
    environment:
      APP_HOST: wger_web_1
      APP_PORT: 8069

  web:
    image: wger/server:master@sha256:20949e499d0c2f2822d37a01537a7ebc90f5d60552cc5eb2bc9e789492ea46ea
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ${APP_DATA_DIR}/config/prod.env
    volumes:
      - ${APP_DATA_DIR}/data/static:/home/wger/static
      - ${APP_DATA_DIR}/data/media:/home/wger/media
    expose:
      - 8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable
    depends_on:
      - web
    volumes:
      - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${APP_DATA_DIR}/data/static:/wger/static:ro
      - ${APP_DATA_DIR}/data/media:/wger/media:ro
    expose:
      - 80
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wger"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cache:
    image: redis
    expose:
      - 6379
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_worker:
    image: wger/server:master@sha256:20949e499d0c2f2822d37a01537a7ebc90f5d60552cc5eb2bc9e789492ea46ea
    command: /start-worker
    env_file:
      - ${APP_DATA_DIR}/config/prod.env
    volumes:
      - ${APP_DATA_DIR}/data/media:/home/wger/media
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "celery -A wger inspect ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_beat:
    image: wger/server:master@sha256:20949e499d0c2f2822d37a01537a7ebc90f5d60552cc5eb2bc9e789492ea46ea
    command: /start-beat
    volumes:
      - ${APP_DATA_DIR}/data/celery-beat:/home/wger/beat/
    env_file:
      - ${APP_DATA_DIR}/config/prod.env
    depends_on:
      celery_worker:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres:
  celery-beat:
  redis:
  media:
  static:

networks:
  default:
    external: true
    name: umbrel_main_network
